# Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 功能建议 / Feature Request
description: 建议此项目的新功能 / Suggest a new idea for this project
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你抽出时间建议新功能！
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: 相关问题 / Is your feature request related to a problem?
      description: 请描述这是否与某个挫败感或问题有关 / Please describe if this is related to a frustration or problem.
      placeholder: 例如：每次我...的时候总是很麻烦 / Ex. I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 期望的功能 / Describe the solution you'd like
      description: 请清晰简洁地描述你希望发生什么 / A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Describe alternatives you've considered
      description: 请描述你考虑过的任何替代解决方案或功能 / A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: 额外上下文 / Additional context
      description: 在此处添加有关功能请求的任何其他上下文或截图 / Add any other context or screenshots about the feature request here.
    validations:
      required: false