name: Auto Label Issues
on:
  issues:
    types: [opened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v9
        with:
          script: |
            const body = context.payload.issue.body || "";
            const labelsToAdd = [];
            if (body.match(/### Kernel Version Category \/ 内核版本分类\s+kernel version 5\.10-/)) labelsToAdd.push("5.10-");
            if (body.match(/### Kernel Version Category \/ 内核版本分类\s+kernel version 5\.10\+/)) labelsToAdd.push("5.10+");
            if (body.match(/### Hook Type \/ Hook 类型\s+susfs/)) labelsToAdd.push("susfs");
            if (body.match(/### Hook Type \/ Hook 类型\s+tracepoint/)) labelsToAdd.push("tracepoint");
            if (body.match(/### Hook Type \/ Hook 类型\s+manual/)) labelsToAdd.push("manual");
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd
              });
            }